### ISSUE TITLE
python train.py fail.

### ISSUE THREAD

**Issue by zy486at189cn** [yangxue0827/R2CNN_FPN_Tensorflow#21]
When I use "python train.py" ,fail.  
My train data is voc_pascal.I success to create pascal_train.tfrecord(2.7G) .
I also change cfgs.py . DATASET_NAME = 'pascal' .
Also success load pre-train file resnet_v1_101.ckpt. 
But finally, report error,just like this:

restore model
Traceback (most recent call last):
  File "tools/train.py", line 238, in <module>
    train()
  File "tools/train.py", line 206, in train
    fast_rcnn_total_loss, total_loss, train_op])
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, gradients/range/delta)]]

Caused by op u'get_batch/batch', defined at:
  File "tools/train.py", line 238, in <module>
    train()
  File "tools/train.py", line 36, in train
    is_training=True)
  File "/media/stockerc/f/wz/project/R2CNN_FPN_Tensorflow/data/io/read_tfrecord.py", line 86, in next_batch
    dynamic_pad=True)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 927, in batch
    name=name)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 722, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 464, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2418, in _queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/stockerc/Tensor1.4/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, gradients/range/delta)]]

Whats matter?@yangxue0827

**Comment by zy486at189cn** [comment]
Thank you ! I find the diffrent. @yangxue0827 
original:<bndbox><xmin>5</xmin><ymin>244</ymin><xmax>67</xmax><ymax>374</ymax>
now:<bndbox><x0>665</x0><y0>572</y0><x1>527</x1><y1>529</y1><x2>695</x2><y2>2</y2><x3>832</x3><y3>45</y3>

**Comment by huiyang865** [comment]
Hi, @zy486at189cn @yangxue0827 
I also meet this problem.  And I have changed the xmin to x0 and so on.
But I can observe that there are four coordinate points in the sample.xml, what these points represent? my xml file just have two coordinate points, which represent the uper left point and lower right point of the box.
My xml content is here, what's wrong with it?
thanks for your help.
````
<annotation>
  <folder>xxx</folder>
  <filename>260001_624_892_663_921_0.jpg</filename>
  <source>
    <database>xxxx</database>
    <annotation>xxxx</annotation>
    <image>xxxx</image>
    <flickrid>0</flickrid>
  </source>
  <owner>
    <name>xxxx</name>
    <flickrid>xxxx</flickrid>
  </owner>
  <size>
    <width>269</width>
    <height>200</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>text</name>
    <pose>Unknown</pose>
    <truncated>1</truncated>
    <difficult>0</difficult>
    <bndbox>
      <x0>97</x0>
      <y0>49</y0>
      <x1>263</x1>
      <y1>180</y1>
    </bndbox>
  </object>
</annotation>
````

**Comment by mengmeng510** [comment]
when I run python train.py,there has a problem:  
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]
  and the xml has no mistake
   Whats matter?@yangxue0827
   thankyou!

**Comment by JisuiWang** [comment]
@yangxue0827  I met the same error as @mengmeng510 .

**Comment by JisuiWang** [comment]
@mengmeng510  I met the same error and I have solved it. Just confirm that your tfrecods is under this path: ${R2CNN_FPN_Tensorflow}/data/tfrecords.

**Comment by zhonhel** [comment]
@JisuiWang 
remain OutOfRangeError

**Comment by zhonhel** [comment]
@yangxue0827 
Hi, if I want to train on Pascal VOC, what should I do to fix this error..?

**Comment by zhonhel** [comment]
@yangxue0827 @JisuiWang 
Solved！That is because some of my xmls contain no object.
