### ISSUE TITLE
trouble testing R2CNN code 

### ISSUE THREAD

**Issue by hh2712** [yangxue0827/R2CNN_FPN_Tensorflow#3]
Hi @yangxue0827 ,
Starred your repo and thanks in advance.

Unfortunately, I had trouble running your inference1.py python script to test your model. Are there any missing installation step before running the script?

Here is a snapshot in the terminal from running inference1.py:
File "inference1.py", line 17, in <module>
    from libs.fast_rcnn import build_fast_rcnn1
  File "../libs/fast_rcnn/build_fast_rcnn1.py", line 14, in <module>
    from libs.box_utils import nms_rotate
  File "../libs/box_utils/nms_rotate.py", line 12, in <module>
    from libs.box_utils.rotate_polygon_nms import rotate_gpu_nms
ImportError: dynamic module does not define module export function (PyInit_rotate_polygon_nms)

Then I tried cd to the ./libs/box_utils/ and ran setup.py script, but failed:

running install
running bdist_egg
running egg_info
writing dependency_links to fast_rcnn.egg-info/dependency_links.txt
writing top-level names to fast_rcnn.egg-info/top_level.txt
writing fast_rcnn.egg-info/PKG-INFO
reading manifest file 'fast_rcnn.egg-info/SOURCES.txt'
writing manifest file 'fast_rcnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
skipping 'rbbox_overlaps.cpp' Cython extension (up-to-date)
building 'rbbox_overlaps' extension
/usr/local/cuda-8.0/bin/nvcc -I/home/administrator/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/include -I/usr/local/cuda-8.0/include -I/usr/include/python3.5m -I/home/administrator/.virtualenvs/cv/include/python3.5m -c rbbox_overlaps_kernel.cu -o build/temp.linux-x86_64-3.5/rbbox_overlaps_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
gcc: error: rbbox_overlaps_kernel.cu: No such file or directory
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/local/cuda-8.0/bin/nvcc' failed with exit status 1

It seems that I am missing rbbox_overlaps_kernel.cu file for some reason.

Please kindly suggest, thank you once again.

Thanks and regards,
Hanyi Hu

**Comment by yangxue0827** [comment]
You can try my docker image first.

**Comment by LQQ0916** [comment]
Hello,I very appreciate your sharing!
But some errors occurred when I run inference1.py
Here's my trouble snapshot:
Traceback (most recent call last):
  File "inference1.py", line 17, in <module>
    from libs.fast_rcnn import build_fast_rcnn1
  File "../libs/fast_rcnn/build_fast_rcnn1.py", line 14, in <module>
    from libs.box_utils import nms_rotate
  File "../libs/box_utils/nms_rotate.py", line 12, in <module>
    from libs.box_utils.rotate_polygon_nms import rotate_gpu_nms
ImportError: dynamic module does not define module export function (PyInit_rotate_polygon_nms)
Please  kindly suggest!
Thanks and regards!

**Comment by jiachen0212** [comment]
i test the inference1.py   but  it do not work, no characters detected！ i haved put the pretrain model in the path .....

**Comment by yangxue0827** [comment]
Please check if you follow the readme steps. For example, did you modify the project's root directory (Line 130 in R2CNN_FPN_Tensorflow\libs\configs\cfgs.py) and if the model was extracted correctly (./R2CNN_FPN_Tensorflow/output/res101_trained_weights/v5/***)

发送自 Windows 10 版邮件应用

发件人: jiachen0212
发送时间: 2018年4月1日 23:05
收件人: yangxue0827/R2CNN_FPN_Tensorflow
抄送: yangxue; Mention
主题: Re: [yangxue0827/R2CNN_FPN_Tensorflow] trouble testing R2CNN code(#3)

i test the inference1.py but it do not work, no characters detected！ i haved put the pretrain model in the path .....

**Comment by csj007** [comment]
I have the same problem. Do you solve it？

**Comment by JackLongKing** [comment]
same problem with detecting nothing

**Comment by JisuiWang** [comment]
I met the same error as 'dynamic module does not define module export function (PyInit_rotate_polygon_nms)', and I solved it just by changing the operating environment from python3 to python2. @hh2712
