### ISSUE TITLE
AttributeError: 'module' object has no attribute 'open'

### ISSUE THREAD

**Issue by gitUserGoodLeaner** [yangxue0827/R2CNN_FPN_Tensorflow#8]
Hi, @yangxue0827 , I faced a problem when I run your training scripts:  python train1.py in your docker environment.
# python train1.py
The error information like these:
Traceback (most recent call last):
  File "train1.py", line 12, in <module>
    import tensorflow.contrib.slim as slim
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 23, in <module>
    from .npyio import *
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 14, in <module>
    from ._datasource import DataSource
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 220, in <module>
    _file_openers = _FileOpeners()
  File "/root/R2CNN_FPN/local/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 162, in __init__
    self._file_openers = {None: io.open}
AttributeError: 'module' object has no attribute 'open'

**Comment by yangxue0827** [comment]
please try python3 train1.py.

**Comment by gitUserGoodLeaner** [comment]
@yangxue0827  Ok, Thanks!  By the way, could you add vgg16 support? Because the Res50 and Res101 have out-of-memory on my GPU device.

**Comment by gitUserGoodLeaner** [comment]
@yangxue0827 I tried the python3 run train1.py, I got error like this:
Traceback (most recent call last):
  File "train1.py", line 21, in <module>
    from libs.fast_rcnn import build_fast_rcnn1
  File "/home/hardDisk/research/workspace/R2CNN_FPN_Tensorflow/tools/../libs/fast_rcnn/build_fast_rcnn1.py", line 14, in <module>
    from libs.box_utils import nms_rotate
  File "/home/hardDisk/research/workspace/R2CNN_FPN_Tensorflow/tools/../libs/box_utils/nms_rotate.py", line 12, in <module>
    from libs.box_utils.rotate_polygon_nms import rotate_gpu_nms
ImportError: dynamic module does not define init function (PyInit_rotate_polygon_nms)
